#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

source ~/.iterm2_shell_integration.zsh

# added by travis gem
[ -f /Users/matt/.travis/travis.sh ] && source /Users/matt/.travis/travis.sh

# added for nodenv
if which nodenv > /dev/null; then eval "$(nodenv init -)"; fi
export NODENV_ROOT=/usr/local/opt/nodenv
#eval "$(nodenv init -)"

# chruby auto switch
source /usr/local/share/chruby/auto.sh

## Custom aliases
alias batt='pmset -g batt'