# `.zshenv' is sourced on all invocations of the shell, unless the -f option is set. It should contain commands to set the command search path, plus other important environment variables. `.zshenv' should not contain commands that produce output or assume the shell is attached to a tty. See http://zsh.sourceforge.net/Intro/intro_3.html

: ${LANG:="en_CA.UTF-8"}
: ${LC_COLLATE:="en_CA.UTF-8"}
: ${LC_CTYPE:="en_CA.UTF-8"}
: ${LC_MESSAGES:="en_CA.UTF-8"}
: ${LC_MONETARY:="en_CA.UTF-8"}
: ${LC_NUMERIC:="en_CA.UTF-8"}
: ${LC_TIME:="en_CA.UTF-8"}
export LANG LC_COLLATE LC_CTYPE LC_MESSAGES LC_MONETARY LC_NUMERIC LC_TIME

# ensure path doesn't get duplicated unnecessarily
typeset -U path

# If run non-interactively, this will set path correctly
# If run interactively, it'll get set then osx will immediately blow it away.
source ~/.zpath

