# Run with `brew bundle`

# Meta
brew "mas"
cask "setapp"


# CLI
brew "eza" # Maintained fork of exa
brew "ripgrep"
cask "warp"

# Communications
# cask "camo-studio"
cask "elgato-stream-deck"
cask "elgato-control-center"
mas "Slack", id: 803453959

# Notes
cask "obsidian"
mas "Tot", id: 1491071483

# Media Handling
mas "Pixelmator Pro", id: 1289583905
cask "vlc"

# Development
brew "gh"
cask "tower"
cask "zed"

# Security
mas "Yubico Authenticator", id: 1497506650

## asdf-vm
brew "coreutils"
brew "curl"
brew "git"
brew "asdf"
